### ISSUE TITLE
[Bug Report] 加密相册无法正常运行

### ISSUE THREAD

**Issue by ChenyqThu** [YunYouJun/hexo-theme-yun#128]
在yun.xml中开启相册：
```
# 开启相册功能
albums:
  enable: true
  icon: icon-gallery-line
  src: /js/gallery-decrypt.js
```
在相册md文件中启用加密：
```
---
title: 韶光如梦
date: 2020-04-18 16:27:24
updated: 2020-04-18 16:27:24
layout: gallery
gallery_password: 141
photos:
  - caption:...
```
未启用Pjax，Hexo S运行后，加密相册无法访问，Git Bash后台报错如下：
![image](https://user-images.githubusercontent.com/84364275/118796099-da95f800-b8cd-11eb-881f-aa7325e6f9d6.png)
