### ISSUE TITLE
[Usage Problem] 为什么 Light 模式的 post-title-link 颜色不是由 primary 来设置的呢？

### ISSUE THREAD

**Issue by LeiWang1999** [YunYouJun/hexo-theme-yun#136]
- 主题版本号（必须）：1.6.1
- 您遇到的问题（必须）：
   比如我现在想把主页里的 post-card 的 title 染成绿色的，在 yun.yml 里设置：

```yml
colors:
  primary: "#98D1D1"
  # bg: "#F5F5F5"
  selection_bg: "#98D1D1" # 选取文字时的背景色
  # 标签云中标签的起始色和结束色
  # tag_start_color:
  # tag_end_color:
```
![image](https://user-images.githubusercontent.com/34334180/124411001-30d7d100-dd7e-11eb-9127-ab1c59a6c2c4.png)

在 Light 模式下的这个卡片的 title 不会改变，我搜了一下样式发现  `themes/yun/source/css/_global/dark.styl` 这个路径下是为 dark 做了 primary 的颜色样式的:

```styl
// post
.post-title-link {
  color: lighten($colors.primary, 30%);
}
```

于是我把主题换成了 dark 模式，这个卡片的 title 的颜色是变了的，

![image](https://user-images.githubusercontent.com/34334180/124411038-46e59180-dd7e-11eb-961e-ce5e70a07924.png)

要做修改的话似乎需要自己写一个 custom.css，但是我想问一下云游君这个设计是有意为之的吗。。这会导致大家的 title 都是蓝色唉。
