### ISSUE TITLE
关于inline公式的问题

### ISSUE THREAD

**Issue by zhoubin-me** [YunYouJun/hexo-theme-yun#204]
主题的inline公式目前测试有不限于以下几个的符号需要转义字符：
- 下划线 ```_```
- 星号 ```*```
- 大括号 ```{ }```
- 转义符 ```\```

比如：
```
$c^* = q_{\alpha, \beta}^* / q^*$
```
需要改为
```
$c^\* = q\_\{\alpha, \beta\}^\* / q^\*$
```

参考其他主题的解决方案：
```
npm un hexo-renderer-marked --save # 如果有安裝這個的話，卸載
npm un hexo-renderer-kramed --save # 如果有安裝這個的話，卸載

npm i hexo-renderer-markdown-it --save # 需要安裝這個渲染插件
npm install @neilsustc/markdown-it-katex --save #需要安裝這個katex插件
```
在 hexo 的根目錄的 _config.yml 中配置
```
markdown:
  plugins:
    - plugin:
      name: '@neilsustc/markdown-it-katex'
      options:
        strict: false
```
