### ISSUE TITLE
[Bug Report]根据文档操作设置代码高亮，但代码却没有正常高亮

### ISSUE THREAD

**Issue by lainbo** [YunYouJun/hexo-theme-yun#237]
```yml
#  根目录的_config.yml
highlight:
  enable: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ""
```

```yml
# themes/yun/_config.yml
codeblock:
  copy_btn: true
  prismjs:
    light: default
    dark: tomorrow
```
重新启动后代码也没有高亮
![image](https://user-images.githubusercontent.com/46062895/148709261-7a8d2723-97a5-430f-83c3-6c75d39d4a7c.png)
