### ISSUE TITLE
[Usage Problem]如何禁用prism-theme-vars的CSS，并启用prismjs的CSS

### ISSUE THREAD

**Issue by 1357310795** [YunYouJun/hexo-theme-yun#272]
主题似乎默认使用
https://cdn.jsdelivr.net/npm/prism-theme-vars/base.css
但是丑得离谱
怎样才能加载
https://cdn.jsdelivr.net/npm/prismjs@latest/themes/prism-coy.css

尝试了下面的配置：
```
(_config.yml)
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: false
  tab_replace: ''
```
```
(_config.yun.yml)
codeblock:
  copy_btn: true
# stylesheets loaded in the <head>
css:
  - /css/hexo-theme-yun.css
  - https://cdn.jsdelivr.net/npm/prismjs@latest/themes/prism-coy.css

```
但是失败了：
![QQ截图20220321151049](https://user-images.githubusercontent.com/35869804/159218005-6bd60fdb-85d2-45a1-9a8a-0eff1e995969.png)

如果`_config.yml`改成
```
(_config.yml)
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: false
  tab_replace: ''
```

![QQ截图20220321151521](https://user-images.githubusercontent.com/35869804/159218480-9755fbf8-12b7-4ad7-b396-9cb64fd91c3e.png)

- 主题版本号（必须）： v1.8.11

**Comment by YunYouJun** [comment]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/25154432/159236628-cf10b14e-65d5-4077-a121-f03fe9a9830d.png">

代码高亮理论上应该是这个样子，并且有亮暗模式。

是否已经使用 `cpp` 作为代码区块命名？

**Comment by 1357310795** [comment]
抱歉之前没看到回复……



> <img alt="image" width="962" src="https://user-images.githubusercontent.com/25154432/159236628-cf10b14e-65d5-4077-a121-f03fe9a9830d.png">
> <img alt="image" width="541" src="https://user-images.githubusercontent.com/25154432/159236829-527b47ec-a3ee-4448-aabe-e7212c3f7f45.png">

这边展示的都是默认的prism-theme-vars的效果，这个是没问题的。但是我想更换成https://cdn.jsdelivr.net/npm/prismjs@latest/themes/prism-coy.css，不知道如何禁用prism-theme-vars的加载

**Comment by YunYouJun** [comment]
Just override it.

```yml
cdn:
  css:
    prism-theme-vars: '' # or your css
```
