### ISSUE TITLE
暗黑主题有没有修改颜色的配置（个人不太喜欢这个黑）

### ISSUE THREAD

**Issue by orcl-zung** [YunYouJun/hexo-theme-yun#273]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by YunYouJun** [comment]
新建一个 styl 文件（参见文档自定义样式）。
然后覆盖对应 css 变量即可。

譬如：

```css
html.dark {
  --hty-bg-color: red;
  --post-block-bg-color: orange;
}
```
