### ISSUE TITLE
[Bug Report]hexo s预览时无法正确加载本地资源

### ISSUE THREAD

**Issue by 1357310795** [YunYouJun/hexo-theme-yun#289]
用的是 npm 包方式进行安装
_config.yml里面设置了url是在一个子目录下
```
url: http://47.xxx.xx.xxx/tech
```

某图片放在\source\img\Akebi-Kao-chan.png
配置文档里使用：
```
sidebar:
  bg_image: source/img/Akebi-Kao-chan.png
  bg_position: bottom 1rem center
  tagcloud:
    enable: false
    amount: 20
```
部署到服务器 http://47.xxx.xx.xxx/tech 后一切正常，但是在本地使用hexo s命令预览，此图片无法加载
（已经执行了hexo g命令）

![image](https://user-images.githubusercontent.com/35869804/167352202-7b2b6f38-3d22-46c1-bf20-70887d8d80c8.png)

**Desktop (please complete the following information):**

- OS: Windows10
- Browser: Microsoft Edge 版本 101.0.1210.39 (正式版本) (64 位)

**主题版本:**
hexo-theme-yun@1.8.11
