### ISSUE TITLE
Demo Sites | 示例站点

### ISSUE THREAD

**Issue by YunYouJun** [YunYouJun/hexo-theme-yun#3]
> 2021-01-09

Move to Discussions https://github.com/YunYouJun/hexo-theme-yun/discussions/97.

---

## 说明

由于目前示例站点已满 24 个，将不会再添加新的示例站点。也希望示例站点列表中的各位能够坚持下去，并保持站点的可访问性。
我会定期访问，如果超过 9 个月没有更新或无法正常访问，我将会将其从中移出，并顺序添加后续留言的可访问站点。

该 ISSUE 将始终保持打开，如果您想分享自己的站点，你仍然可以在此留言。
并在有示例站点被移出时，顺位添加进示例站点。

---

If you are using `hexo-theme-yun`, you can leave your site in this issue.
I will add your site to the demo sites!

## Format

```yml
blog: 云游君的小站
url: https://www.yunyoujun.cn
avatar: avatar.jpg # your avatar url
desc: # describe your site briefly, or the words you like
```

Anything else you want to say~

## Notice:
- New site will not be added when the number of demo sites up to 22. (You can still leave your site here.)
- If your site is no longer using `hexo-theme-yun`, then your site will be removed.

---

如果您正在使用 `hexo-theme-yun`，你可以在这里留下你的站点链接。
我会把它加入示例站点中！

## 格式

```yml
blog: 云游君的小站 # 最好不要太长，控制在八个中文字符宽度内
url: https://www.yunyoujun.cn
avatar: avatar.jpg # 你的头像链接，请确保它为正方形或圆形。
desc: # 简单描述一下你的站点、或者你喜欢的句子
```

其他你想要说的话（畅所欲言～）

## 注意:
- 当示例站点数量到达 24 时，新的站点将不会被添加。（你仍然可以在此留言分享你的站点且作为候补，当示例站点中的用户已不再使用主题 Yun，将顺位添加后续作为示例站点。）
- 如果你的站点不再使用 `hexo-theme-yun`，那么你的站点将会被移除。
- 如果你移除了底部的版权信息或未遵守 [SATA 协议](https://github.com/zTrix/sata-license)，你可以使用它，但将不会被允许添加至此处。
