### ISSUE TITLE
本地搜索功能 位置异常

### ISSUE THREAD

**Issue by huanruomengyun** [YunYouJun/hexo-theme-yun#33]
开启本地搜索后，在本地调试中(hexo s)无异常；部署到云端时，搜索框出现在界面左下角。
云端实际界面
[](https://cdn.jsdelivr.net/gh/huanruomengyun/PicGoBed/issues/gitpage.png)
本地调试界面
[](https://cdn.jsdelivr.net/gh/huanruomengyun/PicGoBed/issues/localsearch.png)

配置如下：

```
# /source/_data/yum.yml
local_search:
  enable: true
  src: /js/search/local-search.js
```
