### ISSUE TITLE
是否可以增加复制文章时追加博客和作者的版权信息的功能？

### ISSUE THREAD

**Issue by ukityh** [YunYouJun/hexo-theme-yun#36]
我大概是没有看到这个功能_(:з)∠)_如果是我自己看漏的话很抱歉！

**Comment by YunYouJun** [comment]
这个功能的确没有，不过实现起来也并不复杂。

我始终没有添加此功能，此前的考虑如下。
譬如一篇技术文章，读者想要拷贝部分脚本代码来复现。剪贴板还带上一堆信息会很麻烦，还需要手动删除。而该功能在复制文章时，对于有心规避版权的人来说，也不过是多按些退格键罢了，只能做到防君子不防小人。
所以为了这部分小人而牺牲大部分读者的体验或许未必值得。

---

当然这个功能我将会作为可选项加上，但因为不是必要项，所以可能需要迟一些等咱有空再实现。

**Comment by YunYouJun** [comment]
@ukityh 您好，该功能已在开发版实现。如果您想要尝试使用的话，可以切换至 `dev` 分支更新。
该功能默认关闭，所以您需要手动配置打开。

```yaml
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true
```

默认追加文章底部的版权信息。

效果如下：

```md
Hexo-Theme-Yun 绝赞开发中~

本文作者：云游君
本文链接：https://www.yunyoujun.cn/note/make-hexo-theme-yun/
版权声明：本博客所有文章除特别声明外，均默认采用 CC BY-NC-SA 4.0 许可协议。
```

如果您有更好的建议，欢迎提出。
