### ISSUE TITLE
yun 通过 hexo-abbrlink 插件优化文章链接失败

### ISSUE THREAD

**Issue by xmuli** [YunYouJun/hexo-theme-yun#39]
**Describe the bug**
hexo 中 yun 主题，使用 hexo-abbrlink 插件优化文章链接，失败

**To Reproduce**
1. 执行 `npm install hexo-abbrlink --save` 安装插件成功； 

2. 在 `blog/_config.yml` 找到相关代码片， 修改为如下：
```
# abbrlink config
abbrlink:
  alg: crc32  # 算法(Algorithm):目前支持crc16和crc32，默认为crc16
  rep: hex    # 表示(Represent):生成的链接可以以十六进制或十进制值表示，默认十进制

```

3. 执行 `hexo clean`，成功

4. 执行 `hexo g`， 失败！！！！

**Expected behavior**
文章顺利生成短链接

**Screenshots**
![image](https://user-images.githubusercontent.com/33887845/86139144-f6f83d00-bb21-11ea-923d-e568f8c32a54.png)

![image](https://user-images.githubusercontent.com/33887845/86138315-e4313880-bb20-11ea-9564-5a57cac3f2fb.png)

**Desktop (please complete the following information):**
```
- MacOs 10.14.6
- Chrome 83.0.4103.116
- hexo: 4.2.1
- hexo-cli: 3.1.0
- os: Darwin 18.7.0 darwin x64
- node: 12.16.3
- v8: 7.8.279.23-node.35
- uv: 1.34.2
- zlib: 1.2.11
- brotli: 1.0.7
- ares: 1.16.0
- modules: 72
- nghttp2: 1.40.0
- napi: 5
- llhttp: 2.0.4
- http_parser: 2.9.3
- openssl: 1.1.1g
- cldr: 36.0
- icu: 65.1
- tz: 2019c
- unicode: 12.1
```

**Additional context**
参考如下博客设置的，都已经尝试过了，但是均失败，然后看到某一篇文章，说是可能主题导致的
[Hexo博客文章链接优化](https://www.xiemingzhao.com/posts/Hexoblogurloptimize.html)
[Hexo博客SEO优化之链接优化](https://www.dazhuanlan.com/2019/08/17/5d5769df44d43/)
[生成永久链接(Permalink) | Hexo](http://blog.jvaeyhcd.wang/posts/05c9df7e0c47bd64.html)

**若是需要我提供更多信息，随时联系我：**
我的站点： https://xmuli.tech
telegram:  [https://t.me/xmuli](https://t.me/xmuli)
github： [https://github.com/xmuli](https://github.com/xmuli)

**Comment by YunYouJun** [comment]
`Cannout read property 'enable' of undefined`

这是 `hexo-abbrlink` 配置没设置吧，`hexo-abbrlink` 前几天更新了，有了新的配置，还没在 `_config.yml` 里添加吧。

**Comment by YunYouJun** [comment]
[hexo-abbrlink](https://github.com/rozbo/hexo-abbrlink)

文档中当前配置：

```yaml
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex
  drafts: false #(true)Process draft,(false)Do not process draft
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true
     depth: 
```

**Comment by xmuli** [comment]
蟹蟹, 晚上我回去后试一下

**Comment by xmuli** [comment]
它是成功的被设置为了短连接，但是从而引进了一个新问题： 归档失败

```bash
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
# permalink: :year/:month/:day/:title/
# permalink_defaults:
permalink: posts/:abbrlink/
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex
  drafts: false #(true)Process draft,(false)Do not process draft
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true
     depth: 

```

设置之前：
![image](https://user-images.githubusercontent.com/33887845/86237957-4ba5c180-bbcf-11ea-969f-36f74ca7db98.png)

设置之后：
![image](https://user-images.githubusercontent.com/33887845/86238010-6415dc00-bbcf-11ea-9fb3-4976e4ac963c.png)


请问， 这个应该如何处理？？？

**Comment by YunYouJun** [comment]
我没有用过 abbrlink，我觉得这可能需要从 hexo-abbrlink 中寻找答案。

以及我的分类方式是在 `frontmatter` 中书写：

```yaml
categories:
  - 云游的小笔记
```

不知您是否已配置类似：

```yaml
catrgories:
  - 学习
  - 技术之外
```

**Comment by YunYouJun** [comment]
或者是否应该关闭此处的自动分类：

```yaml
abbrlink:
  auto_category:
    enable: false
```
