### ISSUE TITLE
网页将代码片的{} 解析为 &#123; 的错误

### ISSUE THREAD

**Issue by xmuli** [YunYouJun/hexo-theme-yun#61]
版本: yun v1.0

使用中，readme 中的代码区域，出现解析错误，右侧为本地文件，左侧为显示网页。其中花括号 `{ }` 被解析为 其它 `&#123;` 这种异常；，，，

附上解析错误的源代码片： [PKGBUILD](https://github.com/xmuli/chinessChess/blob/archlinux/PKGBUILD)
附上解析错误的网页: [对 GNU/Linux 介绍、ArchLinux社区氛围、DDE移植Arch流程](https://xmuli.tech/posts/78cd25f3/)
![image](https://user-images.githubusercontent.com/33887845/92095423-3c7a0480-ee08-11ea-9f2d-bb99754d0aed.png)

**Comment by YunYouJun** [comment]
本地测试正常。

![image](https://user-images.githubusercontent.com/25154432/92105769-e57b2c00-ee15-11ea-970c-2f9acfdf1a9d.png)

是否是 typora 自动转译的问题？可以 `Ctrl` + `?` 查看 typora 源代码。

**Comment by xmuli** [comment]
应该不是主题的原因， 还有其他人也遇到此问。  估计是 hexo 上次更新太新了， mark 一下， [4482](https://github.com/hexojs/hexo/issues/4482)， 回去再研究

**Comment by YunYouJun** [comment]
[Hexo 5.1.1](https://github.com/hexojs/hexo/releases/tag/5.1.1) 应该已经解决了这个问题。

**Comment by xmuli** [comment]
它的修复可能对我的这种也并不适用。从 [＃4489修复不适用于我（无法正确显示代码块中的花括号）](https://github.com/hexojs/hexo/issues/4501) 中来看，我并不是个例子。原因依旧未可知；**但是它的帖子中给出了一个临时的解决方案。也算暂时解决了。**

我的也是最新版本的了；其中 hexo 的 _config.yml 配置如下：

```
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
  
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
```

此两者都是设置的关闭状态。指向 hexo clean 、g、 d 后，还是没有修复。

```bash
hexo: 5.1.1
hexo-cli: 4.2.0
os: Darwin 18.7.0 darwin x64
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```
