### ISSUE TITLE
[Bug Report]正文字体疑似无法修改？

### ISSUE THREAD

**Issue by QingxuMo** [YunYouJun/hexo-theme-yun#73]
在 yun.yml 添加配置如下

```
font:
  cdn:
    enable: true
    lib:
      - https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,700;1,400;1,700&family=Noto+Serif+SC:wght@400;500;700&display=swap
  serif:
    family: "'EB Garamond', 'Noto Serif SC', serif"
    weight: 700
  sans_serif:
    family: "'EB Garamond', 'Noto Serif SC', serif"
    weight: 400
  monospace:
    family: "'EB Garamond', 'Noto Serif SC', serif" #"'Source Code Pro', 'Courier New', Courier, Consolas, Monaco, monospace"
```

实际显示效果来看，博客文章除标题以外都是设备字体而非我设置的姿态。

博客链接：https://qingxu.live

**Comment by YunYouJun** [comment]
`serif/sans_serif/monospace` 分别对应默认的衬线/无衬线/等款字体，查看您的博客，标题及对应使用了等款字体处（不包含文章的 markdown 样式）均已成功修改。
如果您指博文内容，此部分使用了 [star-markdown-css](https://github.com/YunYouJun/star-markdown-css) 中的一种，作为 CDN 引入，不受主题控制（这意味着你可以使用其他任意已有的 markdown css 进行替代）。
而你如果想要对 markdown 样式进行修改，您应该如下自定义样式进行修改。（如果你使用了其他 markdown css，则遵循对应命名空间。）

```css
.markdown-body {
  font-family: 'EB Garamond';
}
```

**Comment by QingxuMo** [comment]
> `serif/sans_serif/monospace` 分别对应默认的衬线/无衬线/等款字体，查看您的博客，标题及对应使用了等款字体处（不包含文章的 markdown 样式）均已成功修改。
> 如果您指博文内容，此部分使用了 [star-markdown-css](https://github.com/YunYouJun/star-markdown-css) 中的一种，作为 CDN 引入，不受主题控制（这意味着你可以使用其他任意已有的 markdown css 进行替代）。
> 
> 而你如果想要对 markdown 样式进行修改，您应该如下自定义样式进行覆盖。（如果你使用了其他 markdown css，则遵循对应命名空间。）
> 
> ```css
> .markdown-body {
>   font-family: 'EB Garamond';
> }
> ```

经反复测试和本地调试，我认为问题不在 Markdown CSS。

我在 source/css/custom.css 中按照上述内容添加了 CSS，但是博客正文字体并没有改变。

我尝试将博客使用的 Markdown CSS 修改为 GitHub 的，博客字体依旧为设备字体。

我简单看了一下 GitHub Markdown CSS 代码，关于字体的代码如下：
```css
.markdown-body input {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}
```
为了进一步验证我的猜测，我创建了一个纯文本的文章，**文章字体依旧为设备字体**。那么基本上可以确定，字体无法修改与 Markdown 无关。

**Comment by YunYouJun** [comment]
请确保已在 `yum.yml` 中配置加载 `custom.css`。（我觉得更可能你自定义没有加载成功。）
或者可以尝试 `!important` 强制覆盖。

```css
.markdown-body {
  font-family: ... !important;
}
```

`input` 只是 markdown-css 中的一个标签，`inherit` 代表继承自 `.markdown-css` 的字体设置。
创建新文章也必然是使用的 `yun-markdown-css`，其中包含默认字体的设置，其他处并没有对 markdown 进行设置。修改自然要覆盖 markdown 样式。

**Comment by QingxuMo** [comment]
> 请确保已在 `yum.yml` 中配置加载 `custom.css`。（我觉得更可能你自定义没有加载成功。）
> 或者可以尝试 `!important` 强制覆盖。
> 
> ```css
> .markdown-body {
>   font-family: ... !important;
> }
> ```
> 
> `input` 只是 markdown-css 中的一个标签，`inherit` 代表继承自 `.markdown-css` 的字体设置。
> 创建新文章也必然是使用的 `yun-markdown-css`，其中包含默认字体的设置，其他处并没有对 markdown 进行设置。修改自然要覆盖 markdown 样式。

查看网页源代码是有显示 custom.css 的……
花了一个多小时把主题源代码看了一遍，暂时没想通为什么无法显示的是设备字体（
先关闭吧，我觉得可能是我的问题

**Comment by YunYouJun** [comment]
说到这个，我想起之前添加了 `post-markdown.styl` 以自定义覆盖字重。只要再简单地添加个字体覆盖即可。

> 当初改为采用 Markdown CSS CDN 的原因则主要出于以下几点的考虑：
> - 用户可以简单地替换 Markdown 样式文件以启用其他任何 Markdown 样式（如与 GitHub Markdown 相同，或其他）
> - Markdown 的 CSS 作为独立文件同样可使用 jsdelivr 加速，提高访问速度
> - 反过来可以将主题风格的 Markdown CSS 用于其他任何地方

效果如下：

```yml
font:
  sans_serif:
      family: "'Songti SC', 'PingFang SC', 'Microsoft YaHei', Roboto, Arial, sans-serif"
      weight: 400
```

![image](https://user-images.githubusercontent.com/25154432/94801983-76472680-0419-11eb-83fa-f8104f9ade25.png)

```yml
font:
  sans_serif:
      family: "'PingFang SC', 'Microsoft YaHei', Roboto, Arial, sans-serif"
      weight: 400
```

![image](https://user-images.githubusercontent.com/25154432/94801892-4ac43c00-0419-11eb-9d7e-7b429fcbbff4.png)
